<a href="https://colab.research.google.com/github/sparsh-goil/DeepLearning-Labs/blob/master/LabAssignment1_201701061.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment 1 : Working with Tensorflow 2.0**
### **Submitted By- 201701061**

In [ ]:
import tensorflow as tf
import math as m

# **1. Series-1**

In [ ]:
def series1(n,x):
  '''
  function for Question-1 series formula in the assignment.
  @args" n- denotes the number of terms in the series. eg. 20,50 or 100. x- denotes the n-dimensional tensor and range of values in x is (0,pi).
  @returns - fx denotes the f(x) of each value of the corresponding arguement x in the function.
  '''
  fx=tf.ones(x.shape)
  for itr in range(2,n+2):
    fx -= ((1 + pow(-1,itr))*tf.math.cos(itr*x))/(m.pow(itr,2) + 1.0)
  fx = fx*(2/m.pi)
  return fx

In [ ]:
#Observations
# x=0.25 & 0.5
print("Observation 1: for n=20")
print(series1(20,tf.constant([0.25,0.5])),"\n----------")
print("Observation 2: for n=50")
print(series1(50,tf.constant([0.25,0.5])),"\n----------")
print("Observation 3: for n=100")
print(series1(100,tf.constant([0.25,0.5])))

Observation 1: for n=20
tf.Tensor([0.40640435 0.5671469 ], shape=(2,), dtype=float32) 
----------
Observation 2: for n=50
tf.Tensor([0.4012348 0.5647007], shape=(2,), dtype=float32) 
----------
Observation 3: for n=100
tf.Tensor([0.4012595 0.5648231], shape=(2,), dtype=float32)


# **2. Mclaurin series**

In [ ]:
def mclaurin(n,x):
  """
  @args: n-denotes the number of terms in the series & x-denotes the n-dimensional tensor and range of values is (0,1).
  @returns : values of fx denotes the f(x) for Mclauran series corresponding to each element in the x tensor.
  """
  fx=tf.zeros(x.shape)
  for itr in range(0,n):
    fx += (pow(-1,itr)*tf.math.pow(x,2*itr*tf.ones(x.shape)))/m.factorial(2*itr)
  return fx

In [ ]:
#Observations
# x=0.25 & 0.5
print("Observation 1: for n=2")
print(mclaurin(2,tf.constant([0.25,0.5])),"\n----------")
print("Observation 2: for n=5")
print(mclaurin(5,tf.constant([0.25,0.5])),"\n----------")
print("Observation 3: for n=10")
print(mclaurin(10,tf.constant([0.25,0.5])))


Observation 1: for n=2
tf.Tensor([0.96875 0.875  ], shape=(2,), dtype=float32) 
----------
Observation 2: for n=5
tf.Tensor([0.9689124 0.8775826], shape=(2,), dtype=float32) 
----------
Observation 3: for n=10
tf.Tensor([0.9689124 0.8775826], shape=(2,), dtype=float32)


# **3. Series-3**

In [ ]:
def series3(n,x):
  '''
  @args: n-denotes the number of terms in the series & x-denotes any n-dimensional tensor having elements in range (0,pi).
  @returns: fx-denotes the values evaluated by f(x) for series-3 in the assignment corresponding to each element in the matrix.
  '''
  fx = tf.zeros(x.shape)
  for itr in range(0,n):
    fx += (m.factorial(2*itr)*tf.math.pow(x,2*itr*tf.ones(x.shape) + 1))/(m.pow(4,itr) * m.pow(m.factorial(itr),2)*(2*itr+1))
  return fx

In [ ]:
#Observations
# x=0.25 & 0.5
print("Observation 1: for n=2")
print(series3(2,tf.constant([0.25,0.5])),"\n----------")
print("Observation 2: for n=5")
print(series3(5,tf.constant([0.25,0.5])),"\n----------")
print("Observation 3: for n=10")
print(series3(10,tf.constant([0.25,0.5])))


Observation 1: for n=2
tf.Tensor([0.25260416 0.5208333 ], shape=(2,), dtype=float32) 
----------
Observation 2: for n=5
tf.Tensor([0.25268024 0.5235852 ], shape=(2,), dtype=float32) 
----------
Observation 3: for n=10
tf.Tensor([0.25268024 0.52359873], shape=(2,), dtype=float32)
